chore: added success check on migration

diff --git a/.codebuild/buildspec.yml b/.codebuild/buildspec.yml
--- a/.codebuild/buildspec.yml
+++ b/.codebuild/buildspec.yml
@@ -123,4 +123,17 @@ phases:
           make migrate;
           make deploy-lambdas-mainnet;
         fi
+      - |
+        if expr "${GIT_REF_TO_DEPLOY}" : "codebuild-debug" >/dev/null; then
+          # Gets all env vars with `dev_` prefix and re-exports them without the prefix
+          for var in "${!dev_@}"; do
+            export ${var#dev_}=${!var}
+          done
+
+          make migrate;
+          if [ $? -ne 0 ]; then
+            echo "Dev migration failed"
+            exit 1
+          fi
+        fi
 
