chore: trigger codebuild

diff --git a/.codebuild/buildspec.yml b/.codebuild/buildspec.yml
--- a/.codebuild/buildspec.yml
+++ b/.codebuild/buildspec.yml
@@ -93,8 +93,8 @@ phases:
       - export GIT_REF_TO_DEPLOY=$(cat git_ref_to_deploy)
   build:
     commands:
-      - set -e
       - |
+        set -e
         if expr "${GIT_REF_TO_DEPLOY}" : "dev" >/dev/null; then
           # Gets all env vars with `dev_` prefix and re-exports them without the prefix
           for var in "${!dev_@}"; do
@@ -105,6 +105,7 @@ phases:
           make deploy-lambdas-dev-testnet;
         fi
       - |
+        set -e
         if expr "${GIT_REF_TO_DEPLOY}" : "master" >/dev/null; then
           # Gets all env vars with `testnet_` prefix and re-exports them without the prefix
           for var in "${!testnet_@}"; do
@@ -115,6 +116,7 @@ phases:
           make deploy-lambdas-testnet;
         fi
       - |
+        set -e
         if expr "${GIT_REF_TO_DEPLOY}" : "v.*" >/dev/null; then
           # Gets all env vars with `mainnet_` prefix and re-exports them without the prefix
           for var in "${!mainnet_@}"; do
@@ -125,22 +127,24 @@ phases:
           make deploy-lambdas-mainnet;
         fi
       - |
+        set -e
         if expr "${GIT_REF_TO_DEPLOY}" : "codebuild-debug" >/dev/null; then
           echo "CODEBUILD-DEBUG"
-          make migrate;
+          # make migrate;
 
-          if [ $? -ne 0 ]; then
-            exit 1
-          fi
-          echo $?
-          echo "Worked even though the migrate failed"
+          # if [ $? -ne 0 ]; then
+          # exit 1
+          # fi
+          # echo $?
+          # echo "Worked even though the migrate failed"
         fi
   post_build:
     commands:
       - |
+        set -e
         if [ $CODEBUILD_BUILD_SUCCEEDING -ne 1 ]; then
           echo "Build phase failed, exiting"
           exit 1
         fi
       - |
-        echo "Didn't exit"
+        echo "Didn't exit, which means the build was successfull"
